batch_size: 32
epochs: 50
accum_iter: 1
visualize_features: true
lr: 0.0001
save_images: false
model_type: copernicusfm
model: vit_b
input_size: 256
dataset_type: geobench_crop
dataset_split: 100
method_name: copernicusfm_vit_b
best_epoch: false
nb_classes: 10
output_dir: /home/filip/satmae_experiments/outputs/
log_dir: /home/filip/satmae_experiments/logs/
finetune: /home/filip/pretrained_weights/CopernicusFM_ViT_base_varlang_e100.pth
# wandb: dl4rs-experiments
eval: true
dist_eval: true
num_workers: 10
