batch_size: 64
epochs: 50
accum_iter: 1
visualize_features: false
lr: 0.001
save_images: false
model_type: copernicusfm
model: vit_b
input_size: 120
dataset_type: geobench_bigearthnet
dataset_split: 10
method_name: copernicusfm_vit_b
best_epoch: false
nb_classes: 43
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
finetune: /home/filip/pretrained_weights/CopernicusFM_ViT_base_varlang_e100.pth
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
