batch_size: 16
epochs: 50
accum_iter: 4
visualize_features: false
lr: 0.01
save_images: false
model_type: dinov2_segmentation
model: base_0
input_size: 64
dataset_type: geobench_eurosat
dataset_split: 100
method_name: basev2_b
best_epoch: false
nb_classes: 10
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
