batch_size: 16
epochs: 50
accum_iter: 4
visualize_features: false
lr: 0.001
save_images: false
model_type: dinov2_segmentation
model: basev3_0
input_size: 256
dataset_type: geobench_crop
dataset_split: 100
method_name: dinov3_b
best_epoch: false
nb_classes: 10
output_dir: /home/filip/satmae_experiments/outputs/
log_dir: /home/filip/satmae_experiments/logs/
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
