batch_size: 16
epochs: 50
accum_iter: 4
visualize_features: false
lr: 0.001
save_images: false
model_type: dinov2_segmentation
model: largev3_0
input_size: 320
dataset_type: geobench_pv
dataset_split: 100
method_name: dinov3_l_SAT
best_epoch: false
nb_classes: 2
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
