batch_size: 8
epochs: 50
lr: 0.001
accum_iter: 8
visualize_features: false
save_images: true
model_type: dinov2_segmentation
model: largev3_0
input_size: 512
dataset_type: sen1floods11
dataset_split: 100
method_name: dinov3_l_SAT
best_epoch: false
nb_classes: 3
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
