batch_size: 32
epochs: 50
accum_iter: 2
visualize_features: false
lr: 0.0001
save_images: false
model_type: simdino
model: swin_b
input_size: 224
dataset_type: spacenet
dataset_split: 100
method_name: swin_bm_ms_fmow_hr_500k_100e_dinov3p34c_rgb_head_dconv_aug
best_epoch: false
nb_classes: 2
output_dir: /home/filip/satmae_experiments/outputs/
log_dir: /home/filip/satmae_experiments/logs/
finetune: /home/filip/satmae_experiments/outputs/swin_bm_ms_fmow_hr_500k_100e_dinov3p34c_rgb_head_dconv_aug/best_model_checkpoint_spacenet_100.pth
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
