batch_size: 16
epochs: 50
accum_iter: 4
lr: 0.0001
visualize_features: false
save_images: true
model_type: dinov2_segmentation
model: largev3_0
input_size: 224
dataset_type: spacenet
dataset_split: 100
method_name: dinov3_l_SAT
best_epoch: false
nb_classes: 2
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
